/*Import FontAwesomeIcon*/
import {library} from "@fortawesome/fontawesome-svg-core";
import {
    faTv,
    faPlug,
    faWindowRestore,
    faChartBar,
    faBookmark,
    faTable,
    faWindowMaximize,
    faLayerGroup,
    faGripHorizontal,
    faEdit,
    faEye,
    faRetweet,
    faClock,
    faCode,
    faQuestion,
    faCog,
    faStar,
    faChevronDown,
    faEllipsisVertical,
    faCircleInfo,
    faMoneyCheckDollar,
    faPercent,
    faDollarSign,
    faRubleSign,
    faUserGraduate
} from "@fortawesome/free-solid-svg-icons";


library.add(
    faTv,
    faPlug,
    faWindowRestore,
    faChartBar,
    faBookmark,
    faTable,
    faWindowMaximize,
    faLayerGroup,
    faGripHorizontal,
    faEdit,
    faEye,
    faRetweet,
    faClock,
    faCode,
    faQuestion,
    faCog,
    faStar,
    faChevronDown,
    faEllipsisVertical,
    faCircleInfo,
    faMoneyCheckDollar,
    faPercent,
    faDollarSign,
    faRubleSign,
    faUserGraduate
)
